algoritmo "Calculadora"
// Função :Cálculos de juros compostos
// Autor : Cristiano Zanguetin FAntin
// Data : 10/02/2021
// Seção de Declarações  uso do git
var
  soma, num1, num2:real

inicio
  escreval("Informe o valor inicial: ")
  leia(num1)
  
  escreval("Informe o valor das parcelas: ")
  leia(num2)


  soma := num1 + num2
        escreval("A soma de ", num1, " e ",num2, " é igual a  " , soma)
        


fimalgoritmo